name: Hello
on: push
jobs:
  hello:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ vars.USERNAME }}
    steps:
    - run: echo "Hello, world"
    - run: echo "$USERNAME"
    - uses: actions/checkout@v4